language: cpp

os: osx

before_script:
  # install emscripten
  - wget https://s3.amazonaws.com/mozilla-games/emscripten/releases/emsdk-portable.tar.gz
  - tar xvzf emsdk-portable.tar.gz
  - cd emsdk-portable
  - ./emsdk update
  - ./emsdk install sdk-1.8.2-64bit
  - ./emsdk activate emscripten-1.8.2
  - source ./emsdk_env.sh
  - cat ~/.emscripten
  - echo "LLVM_ROOT='$(pwd)/clang/3.2_64bit/bin/'" >> ~/.emscripten
  - cd ..

script: make
